{
 "title": "Financial Health",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Savings Objectives",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "categories",
     "query": "SELECT \"goalPercentageComplete\" AS \"Savings Category A\" FROM \"categories\" WHERE (\"category\" = 'Savings Category A')",
     "select": [
      [
       { "params": [ "goalPercentageComplete" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Savings Category A" }
     ]
    },
    {
     "measurement": "categories",
     "query": "SELECT \"goalPercentageComplete\" AS \"Savings Category B\" FROM \"categories\" WHERE (\"category\" = 'Savings Category B')",
     "select": [
      [
       { "params": [ "goal_percentage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Savings Category B" }
     ]
    },
    {
     "measurement": "categories",
     "query": "SELECT \"goalPercentageComplete\" AS \"Savings Category C\" FROM \"categories\" WHERE (\"category\" = 'Savings Category C')",
     "select": [
      [
       { "params": [ "goal_percentage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Savings Category C" }
     ]
    },
    {
     "measurement": "categories",
     "query": "SELECT \"goalPercentageComplete\" AS \"Savings Category D\" FROM \"categories\" WHERE (\"category\" = 'Savings Category D')",
     "select": [
      [
       { "params": [ "goal_percentage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Savings Category D" }
     ]
    }
   ]
  },
  {
   "title": "Cash Flow By Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "transactions",
     "query": "SELECT sum(\"amount\") AS \"Expense\" FROM \"transactions\" WHERE $timeFilter AND (\"payee\" !~ /Transfer*/ AND \"payee\" !~ /Payment*/ AND \"payee\" !~ /Starting*/) AND \"amount\" < 0 GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "payee", "operator": "!=", "value": "Transfer" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"amount\")/2 AS \"Income\" FROM \"transactions\" WHERE $timeFilter AND (\"category\" = 'To be Budgeted') AND \"amount\" > 0 GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "To be Budgeted" }
     ]
    }
   ]
  },
  {
   "title": "Top 10 Expenses",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transactions",
     "query": "SELECT \"payee\" as \"Payee\",bottom(\"amount\",10) AS \"Amount\" FROM (SELECT \"amount\",\"payee\" FROM \"transactions\" WHERE $timeFilter AND \"amount\" < 0 AND (\"payee\" !~ /Transfer*/ AND \"payee\" !~ /Starting*/))",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Income",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 6 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "alias": "Income Source B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "transactions",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "payee", "operator": "=", "value": "Income Source B" }
     ]
    },
    {
     "alias": "Income Source A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "transactions",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "payee", "operator": "=", "value": "Income Source A" }
     ]
    }
   ]
  },
  {
   "title": "Net Gain/Loss",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Expenses",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "categories",
     "query": "SELECT sum(\"activity\") FROM (SELECT last(\"activity\") as \"activity\" FROM \"categories\" WHERE $timeFilter AND (\"categoryGroup\" != 'Credit Card Payments' AND \"deleted\" = 'False' AND \"hidden\" = 'False') AND activity < 0 GROUP BY \"category\")",
     "select": [
      [
       { "params": [ "activity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "categoryGroup", "operator": "!=", "value": "Credit Card Payments" },
      { "condition": "AND", "key": "deleted", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "hidden", "operator": "=", "value": "False" }
     ]
    },
    {
     "alias": "Income",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"activity\") FROM (SELECT last(\"activity\") as \"activity\" FROM \"categories\" WHERE $timeFilter AND (\"categoryGroup\" != 'Credit Card Payments' AND \"deleted\" = 'False' AND \"hidden\" = 'False') AND activity > 0 GROUP BY \"category\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Account Balances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "$tag_account",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "account" ], "type": "tag" }
     ],
     "measurement": "accounts",
     "query": "SELECT last(\"balance\") FROM \"accounts\" WHERE (\"type\" = 'otherAsset') OR (\"on_budget\" = 'True' AND \"type\" != 'creditCard') AND $timeFilter GROUP BY time($__interval), \"account\"",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "on_budget", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "type", "operator": "!=", "value": "creditCard" }
     ]
    }
   ]
  },
  {
   "title": "Debt",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "$tag_account",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "account" ], "type": "tag" }
     ],
     "measurement": "accounts",
     "query": "SELECT last(\"balance\") FROM \"accounts\" WHERE $timeFilter AND \"type\" != 'otherAsset' AND (\"type\" = 'creditCard' OR \"on_budget\" = 'False') GROUP BY time($__interval), \"account\"",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "on_budget", "operator": "=", "value": "False" }
     ]
    }
   ]
  }
 ]
}